### ISSUE TITLE
Use Hand Grab cursor when dragging

### ISSUE THREAD

**Issue by sguergachi** [davidparsson/ScrollbarAnywhere#31]
The Hand Grab cursor, on windows I think is a more appropriate cursor then the 4 point icons currently used to represent dragging

**Comment by davidparsson** [comment]
This is now supported via CSS3:

    cursor: -webkit-grabbing;

**Comment by davidparsson** [comment]
Fixed by #42.

**Comment by natostanco** [comment]
what icon is used by the css rule? Does chrome use a custom hand grab icon? Because the icon used in my case is not the one from the X theme

**Comment by davidparsson** [comment]
It's provided by Chrome, not by this extension:

      document.body.style.cursor = "-webkit-grabbing";
      document.body.style.cursor = "grabbing";

**Comment by natostanco** [comment]
yes indeed, to display the os icon the correct option is either:
`curosr: move` 
`cursor: all-scroll`
maybe an option can be added to choose the preferred css value

**Comment by davidparsson** [comment]
The `all-scroll` icon was used before the grabbing hand was introduced, but i think the grabbing hand is preferable in most cases. I'm willing to accept a pull request that adds a configurable option for this, but I won't implement it myself. If the cursor icon bothers you it's possible to disable the cursor switching entirely.
