### ISSUE TITLE
Port extension to Atom?

### ISSUE THREAD

**Issue by iliyang** [davidparsson/ScrollbarAnywhere#45]
ScrollbarAnywhere is hands down my favorite extension! It would be absolutely awesome if it could be ported to the Atom text editor. I hope this won't be too hard to do, since Atom is also built on top of the Chromium framework and every UI element is actually an HTML element.

**Comment by davidparsson** [comment]
Hi,

Thank you, it nice to hear that you like the extension. I don't use Atom, and I don't really have the time required to maintain a port. The source code is right here though, so if you're willing you may fork it and give it a try your self. Best of luck!
